
name: cron
on:
  schedule:
    # runs tests every day at 3am
    - cron: '0 3 * * *'
jobs:
  nightly:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress nightly tests 🌃
        uses: cypress-io/github-action@v5
