
name: nightly tests
on:
  schedule:
    # runs tests every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  nightly:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress nightly tests 🌃
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
